# Generated by Django 3.1.3 on 2020-12-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=50, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
