# Generated by Django 2.1.3 on 2018-11-14 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='cod',
        ),
    ]
