# Generated by Django 2.1.3 on 2018-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_bicicleta_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='comuna',
            field=models.CharField(choices=[('La Reina', 'La Reina'), ('Providencia', 'Providencia'), ('Ñuñoa', 'Ñuñoa')], default='La Reina', max_length=2),
            preserve_default=False,
        ),
    ]
