# Generated by Django 2.1.3 on 2018-11-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_persona_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='cod',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]