# Generated by Django 2.1.3 on 2018-11-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_bicicleta_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='comuna',
            field=models.CharField(choices=[('La Reina', 'La Reina'), ('Providencia', 'Providencia'), ('Ñuñoa', 'Ñuñoa')], max_length=20),
        ),
    ]
