# Generated by Django 3.1.3 on 2020-12-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20181114_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cred',
            field=models.IntegerField(default=1),
        ),
    ]
