# Generated by Django 3.1.3 on 2020-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20201202_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='is_disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='marca',
            field=models.CharField(default='shimano', max_length=30),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='modelo',
            field=models.CharField(default='ETP-765', max_length=30),
        ),
    ]
