# Generated by Django 3.1.3 on 2020-12-02 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20201202_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prod', models.IntegerField()),
                ('nom_prod', models.CharField(max_length=30)),
                ('desc_prod', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('is_disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(default='deprueba@gmail.com', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='direccion de prueba 123', max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=30),
        ),
    ]
