# Generated by Django 3.1.3 on 2020-12-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20201202_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bicicleta',
        ),
    ]
