# Generated by Django 3.1.2 on 2020-10-31 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cuenta',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='pseudonimo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
